SystemOrganization addCategory: #TypeAnnotation!
SystemOrganization addCategory: 'TypeAnnotation-Compiler'!
SystemOrganization addCategory: 'TypeAnnotation-Editing'!
SystemOrganization addCategory: 'TypeAnnotation-EditorExample'!
SystemOrganization addCategory: 'TypeAnnotation-Node'!
SystemOrganization addCategory: 'TypeAnnotation-Parser'!
SystemOrganization addCategory: 'TypeAnnotation-Semantic'!
